# TODO: stop using this semi-random image
image: "adbourne/docker-java-maven-protobuf:v3.5-8-3.5.0"

stages:
  - build
  - test

# This folder is cached between builds
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

# TODO: set a share cache path
build:
  stage: build
  script:
    - ./gradlew --build-cache assemble

test:
  stage: test
  script: ./gradlew check
