image: "registry.gitlab.com/whylabs/docker-images:13ae56985c0aa07aa07022c5771072dac8750dff"
stages:
  - build
  - test
  - publish

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: $CI_PROJECT_NAME
  paths:
    - .gradle/wrapper/
    - .gradle/caches/
    - build/
    - mobile/build/
    - wear/build/
    - .cache/pip
    - venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - aws codeartifact login --region us-west-2 --tool pip --repository python-dev --domain dev --domain-owner 207285235248

build:java:
  stage: build
  script:
    - ./gradlew --build-cache assemble -PisGitLabCi=true -x :whylogs-python:build build

build:python:
  stage: build
  script:
    - ./gradlew :whylogs-python:build build

test:java:
  stage: test
  script: ./gradlew check -PisGitLabCi=true
  needs: ["build:java"]

test:python:
  stage: test
  script: ./gradlew check -PisGitLabCi=true
  needs: ["build:python"]

publish:tag:
  stage: publish
  script:
    - cd whylogs-whypthon && pip install twine
    - aws codeartifact login --region us-west-2 --tool twine --repository python-dev --domain dev --domain-owner 207285235248
    - ./gradlew publish-python
  rules:
    - if: '$CI_COMMIT_TAG != null'
  needs: ["test:python"]

publish:release:
  stage: publish
  script:
    - cd whylogs-whypthon && pip install twine
    - aws codeartifact login --region us-west-2 --tool twine --repository python-dev --domain dev --domain-owner 207285235248
    - ./gradlew publish-python
  needs: ["test:python"]
  only:
    refs:
      - release
