# TODO: stop using this semi-random image
image: "andifire/openjdk8-python37:latest"

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
  key: $CI_PROJECT_NAME
  paths:
    - .gradle/wrapper/
    - .gradle/caches/
    - build/
    - mobile/build/
    - wear/build/

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

# TODO: set a share cache path
build:
  stage: build
  script:
    - ./gradlew --build-cache assemble -PisGitLabCi=true

test:
  stage: test
  script: ./gradlew check -PisGitLabCi=true
