# TODO: build this image automatically
image: "andifire/openjdk8-python37:0.3"

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: $CI_PROJECT_NAME
  paths:
    - .gradle/wrapper/
    - .gradle/caches/
    - build/
    - mobile/build/
    - wear/build/
    - .cache/pip
    - venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble -PisGitLabCi=true

test:
  stage: test
  script: ./gradlew check -PisGitLabCi=true
