#!/bin/sh

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../

echo "Base dir: $DIR"

git diff --quiet
hadNoNonStagedChanges=$?
if ! [ $hadNoNonStagedChanges -eq 0 ]; then
  echo "* Stashing non-staged changes"
  git stash --keep-index -u >/dev/null
fi

(cd "$DIR" && ./gradlew spotlessJavaCheck --daemon)
RESULT=$?
echo "* Properly formatted?"

if [ $RESULT -eq 0 ]; then
  echo "* Yes"
  echo "Running tests"
  ./gradlew test --daemon
  RESULT=$?
else
  echo "* No"
  echo "Please run './gradlew spotlessApply' to format the code."
  echo ""
fi

if ! [ $hadNoNonStagedChanges -eq 0 ]; then
  echo "$(tput setaf 3)* Scheduling stash pop of previously stashed non-staged changes for 1 second after commit.$(tput sgr 0)"
  sleep 1 && git stash pop --index >/dev/null &# sleep and & otherwise commit fails when this leads to a merge conflict
fi

exit $RESULT
