name: Python application

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install Protoc
      uses: arduino/setup-protoc@master
    - name: Build Python
      env:
        AWS_ACCESS_KEY_ID: foo
        AWS_SECRET_ACCESS_KEY: bar
      run: |
        ./gradlew :whylogs-python:build build
